# Generated by Django 3.0.5 on 2021-02-15 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cpf', models.CharField(max_length=11, primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Cliente')),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=11, null=True, verbose_name='Nº celular')),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(choices=[('R', 'Residencial'), ('C', 'Comercial'), ('O', 'Outros')], max_length=3)),
                ('logradouro', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=6)),
                ('complemento', models.CharField(blank=True, max_length=50, null=True)),
                ('bairro', models.CharField(max_length=100, null=True)),
                ('cidade', models.CharField(max_length=50, null=True)),
                ('cep', models.CharField(max_length=9, null=True)),
                ('uf', models.CharField(max_length=2, null=True)),
            ],
        ),
    ]
