# Generated by Django 3.0.5 on 2021-02-15 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_endereco_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='endereco',
            field=models.CharField(choices=[('1', 'Residencial'), ('2', 'Comercial'), ('3', 'Outros')], max_length=3),
        ),
    ]
